site:
    title: CUBA 前端 UI 开发手册
    url: https://doc.cuba-platform.cn/frontend
    start_page: cuba-frontend-docs:overview:index.adoc
output:
    dir: docs-build
content:
    sources:
        - url: https://github.com/cuba-platform/frontend.git
          branches:
              - master
          #        - v[0-9]*
          start_path: docs-src-cn/doc-component-repo
ui:
    bundle:
        url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
        snapshot: true
    supplemental_files: ./supplemental-ui
asciidoc:
    attributes:
        manual_platform: 'https://doc.cuba-platform.cn/manual-latest'
        manual_restApi: 'https://doc.cuba-platform.cn/restapi-7.2'
        manual_studio: 'https://doc.cuba-platform.cn/studio-chs'
        manual_studio_frontendUi: 'https://doc.cuba-platform.cn/studio-chs/#frontend_ui'
        restApiSwagger: 'http://files.cuba-platform.com/swagger/7.2'
        compositionGuide: 'https://www.cuba-platform.cn/guides/data-modelling-composition'
        petclinic: 'https://github.com/cuba-platform/cuba-petclinic'
        # TODO Change this link to https://ant.design once https://github.com/cuba-platform/frontend/issues/168 is implemented
        antDesign_base: 'https://ant.design'
        npm_frontendGenerator: 'https://www.npmjs.com/package/@cuba-platform/front-generator'
        npm_cubaReactCore: 'https://www.npmjs.com/package/@cuba-platform/react-core'
        npm_cubaReactUi: 'https://www.npmjs.com/package/@cuba-platform/react-ui'
        npm_cubaRestJs: 'https://www.npmjs.com/package/@cuba-platform/rest'
        forum: 'https://forum.cuba-platform.cn'
        api_rest: 'link:../api-reference/cuba-rest-js/index.html'
        git_frontendUi: 'https://github.com/cuba-platform/frontend'
