-- begin SCR_FAVORITE_CAR
alter table SCR_FAVORITE_CAR add constraint FK_SCR_FAVORITE_CAR_CAR foreign key (CAR_ID) references SCR_CAR(ID)^
alter table SCR_FAVORITE_CAR add constraint FK_SCR_FAVORITE_CAR_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SCR_FAVORITE_CAR_CAR on SCR_FAVORITE_CAR (CAR_ID)^
create index IDX_SCR_FAVORITE_CAR_USER on SCR_FAVORITE_CAR (USER_ID)^
-- end SCR_FAVORITE_CAR
-- begin SCR_CAR
alter table SCR_CAR add constraint FK_SCR_CAR_GARAGE foreign key (GARAGE_ID) references SCR_GARAGE(ID)^
alter table SCR_CAR add constraint FK_SCR_CAR_TECHNICAL_CERTIFICATE foreign key (TECHNICAL_CERTIFICATE_ID) references SCR_TECHNICAL_CERTIFICATE(ID)^
alter table SCR_CAR add constraint FK_SCR_CAR_PHOTO foreign key (PHOTO_ID) references SYS_FILE(ID)^
create index IDX_SCR_CAR_GARAGE on SCR_CAR (GARAGE_ID)^
create index IDX_SCR_CAR_PHOTO on SCR_CAR (PHOTO_ID)^
-- end SCR_CAR
-- begin SCR_CAR_RENT
alter table SCR_CAR_RENT add constraint FK_SCR_CAR_RENT_CAR foreign key (CAR_ID) references SCR_CAR(ID)^
create index IDX_SCR_CAR_RENT_CAR on SCR_CAR_RENT (CAR_ID)^
-- end SCR_CAR_RENT
-- begin SCR_SPARE_PART
alter table SCR_SPARE_PART add constraint FK_SCR_SPARE_PART_SPARE_PARTS foreign key (SPARE_PARTS_ID) references SCR_SPARE_PART(ID)^
create index IDX_SCR_SPARE_PART_SPARE_PARTS on SCR_SPARE_PART (SPARE_PARTS_ID)^
-- end SCR_SPARE_PART
-- begin SCR_GARAGE_USER_LINK
alter table SCR_GARAGE_USER_LINK add constraint FK_GARUSE_GARAGE foreign key (GARAGE_ID) references SCR_GARAGE(ID);
alter table SCR_GARAGE_USER_LINK add constraint FK_GARUSE_USER foreign key (USER_ID) references SEC_USER(ID);
-- end SCR_GARAGE_USER_LINK
-- begin SCR_ASSOCIATION_O2M_TEST_ENTITY
alter table SCR_ASSOCIATION_O2M_TEST_ENTITY add constraint FK_SCR_ASSOCIATION_O2M_TEST_ENTITY_DATATYPES_TEST_ENTITY foreign key (DATATYPES_TEST_ENTITY_ID) references SCR_DATATYPES_TEST_ENTITY(ID)^
create index IDX_SCR_ASSOCIATION_O2M_TEST_ENTITY_DATATYPES_TEST_ENTITY on SCR_ASSOCIATION_O2M_TEST_ENTITY (DATATYPES_TEST_ENTITY_ID)^
-- end SCR_ASSOCIATION_O2M_TEST_ENTITY
-- begin SCR_COMPOSITION_O2M_TEST_ENTITY
alter table SCR_COMPOSITION_O2M_TEST_ENTITY add constraint FK_SCR_COMPOSITION_O2M_TEST_ENTITY_DATATYPES_TEST_ENTITY foreign key (DATATYPES_TEST_ENTITY_ID) references SCR_DATATYPES_TEST_ENTITY(ID)^
create index IDX_SCR_COMPOSITION_O2M_TEST_ENTITY_DATATYPES_TEST_ENTITY on SCR_COMPOSITION_O2M_TEST_ENTITY (DATATYPES_TEST_ENTITY_ID)^
-- end SCR_COMPOSITION_O2M_TEST_ENTITY
-- begin SCR_DATATYPES_TEST_ENTITY
alter table SCR_DATATYPES_TEST_ENTITY add constraint FK_SCR_DATATYPES_TEST_ENTITY_ASSOCIATION_O2_OATTR foreign key (ASSOCIATION_O2_OATTR_ID) references SCR_ASSOCIATION_O2O_TEST_ENTITY(ID)^
alter table SCR_DATATYPES_TEST_ENTITY add constraint FK_SCR_DATATYPES_TEST_ENTITY_ASSOCIATION_M2_OATTR foreign key (ASSOCIATION_M2_OATTR_ID) references SCR_ASSOCIATION_M2O_TEST_ENTITY(ID)^
alter table SCR_DATATYPES_TEST_ENTITY add constraint FK_SCR_DATATYPES_TEST_ENTITY_COMPOSITION_O2_OATTR foreign key (COMPOSITION_O2_OATTR_ID) references SCR_COMPOSITION_O2O_TEST_ENTITY(ID)^
create index IDX_SCR_DATATYPES_TEST_ENTITY_ASSOCIATION_M2_OATTR on SCR_DATATYPES_TEST_ENTITY (ASSOCIATION_M2_OATTR_ID)^
-- end SCR_DATATYPES_TEST_ENTITY
-- begin SCR_DATATYPES_TEST_ENTITY_ASSOCIATION_M2M_TEST_ENTITY_LINK
alter table SCR_DATATYPES_TEST_ENTITY_ASSOCIATION_M2M_TEST_ENTITY_LINK add constraint FK_DATTESENTASSM2MTESENT_DATATYPES_TEST_ENTITY foreign key (DATATYPES_TEST_ENTITY_ID) references SCR_DATATYPES_TEST_ENTITY(ID)^
alter table SCR_DATATYPES_TEST_ENTITY_ASSOCIATION_M2M_TEST_ENTITY_LINK add constraint FK_DATTESENTASSM2MTESENT_ASSOCIATION_M2_M_TEST_ENTITY foreign key (ASSOCIATION_M2_M_TEST_ENTITY_ID) references SCR_ASSOCIATION_M2M_TEST_ENTITY(ID)^
-- end SCR_DATATYPES_TEST_ENTITY_ASSOCIATION_M2M_TEST_ENTITY_LINK
-- begin SCR_COMPOSITION_O2O_TEST_ENTITY
alter table SCR_COMPOSITION_O2O_TEST_ENTITY add constraint FK_SCR_COMPOSITION_O2O_TEST_ENTITY_NESTED_COMPOSITION foreign key (NESTED_COMPOSITION_ID) references SCR_DEEPLY_NESTED_TEST_ENTITY(ID)^
-- end SCR_COMPOSITION_O2O_TEST_ENTITY

-- begin SCR_DEEPLY_NESTED_TEST_ENTITY
alter table SCR_DEEPLY_NESTED_TEST_ENTITY add constraint FK_SCR_DEEPLY_NESTED_TEST_ENTITY_ASSOCIATION_O2_OATTR foreign key (ASSOCIATION_O2_OATTR_ID) references SCR_ASSOCIATION_O2O_TEST_ENTITY(ID)^
-- end SCR_DEEPLY_NESTED_TEST_ENTITY
-- begin SCR_DATATYPES_TEST_ENTITY2
alter table SCR_DATATYPES_TEST_ENTITY2 add constraint FK_SCR_DATATYPES_TEST_ENTITY2_DATATYPES_TEST_ENTITY_ATTR foreign key (DATATYPES_TEST_ENTITY_ATTR_ID) references SCR_DATATYPES_TEST_ENTITY(ID)^
-- end SCR_DATATYPES_TEST_ENTITY2
