= SpecificPermAccessControl
:api_core_SpecificPermAccessControlProps: link:../api-reference/jmix-react-core/interfaces/_access_control_specificpermaccesscontrol_.specificpermaccesscontrolprops.html

`SpecificPermAccessControl` is used to conditionally render other components (which we call _access-controlled components_) based on a single or multiple specific permissions.

Use this component either by wrapping access-controlled components in it:

[source,typescript]
----
<SpecificPermAccessControl perm='cuba.restApi.fileUpload.enabled'>
  <button>Upload File</button>
</SpecificPermAccessControl>
----

or by providing a https://reactjs.org/docs/render-props.html[render prop]:

[source,typescript]
----
<SpecificPermAccessControl perm='cuba.restApi.fileUpload.enabled'
                           render={disabled => <button disabled={disabled}>Upload File</button>}
/>
----

If both are provided, render prop takes precedence.

In either example the button will only be shown when a user has a permission to upload files.

To specify multiple required permissions, use an array:

[source,typescript]
----
<SpecificPermAccessControl perm={['cuba.restApi.fileUpload.enabled', 'some.custom.specific.permission']}>
  <button>Upload File</button>
</SpecificPermAccessControl>
----

Instead of hiding the access-controlled components you can specify to render them as disabled by setting `mode` prop to `disable`. If `mode` is `disable`:

* If render prop is used, it will receive `true` as its `disabled` parameter.
* Otherwise a prop with name `disabled` (can be configured via `disabledPropName` prop) and value `true` (can be configured via `disabledPropValue` prop) will be passed to each child.

'''

API: {api_core_SpecificPermAccessControlProps}[SpecificPermAccessControlProps].

See also:

* xref:access-control.adoc[AccessControl]
* xref:entity-perm-access-control.adoc[EntityPermAccessControl]
* xref:attr-perm-access-control.adoc[AttrPermAccessControl]
* link:{manual_platform}/security[Security in Jmix]
