# coverage check config

extends: "@istanbuljs/nyc-config-typescript"
check-coverage: true
skip-full: true

# do not check coverage in this folders
exclude: [
  "src/test/**",
  "src/generators/*/*/template/**",
]

statements: 79
branches: 64
functions: 77
lines: 79
