= EntityPermAccessControl
:api_core_EntityPermAccessControlProps: link:../api-reference/cuba-react-core/interfaces/_access_control_entitypermaccesscontrol_.entitypermaccesscontrolprops.html
:experimental:

`EntityPermAccessControl` 用来根据单一实体操作权限有条件的渲染其他组件（我们称之为 _access-controlled components_）。最常见的用法是在实体列表中，有条件的隐藏 btn:[Create] / btn:[Edit] / btn:[Delete] 按钮。

使用时，可以将 access-controlled components 包在该组件内部：

[source,typescript]
----
<EntityPermAccessControl entityName='scr$Car' operation='create'>
  <button>Do Something</button>
</EntityPermAccessControl>
----

也可以通过 https://reactjs.org/docs/render-props.html[render] 属性提供：

[source,typescript]
----
<EntityPermAccessControl entityName='scr$Car'
                         operation='create'
                         render={disabled => <button disabled={disabled}>Do Something</button>}
/>
----

如果两种方式同时使用，那么 render 属性优先级更高。

上面两个例子中，只有当用户有权限创建 `scr$Car` 实体实例时，按钮才会显示。

除了隐藏 access-controlled components 之外，还可以通过设置 `mode` 属性为 `disable` 来禁用组件。如果 `mode` 是 `disable`：

* 如果提供了 render 属性，那么该属性中组件的 disabled 参数会接收 `true`
* 否则，每个子组件都会收到一个名称为 `disabled` 值为 `true` 的属性。属性名称可以通过 `disabledPropName` 设置，值可以通过 `disabledPropValue` 设置。

'''

API: {api_core_EntityPermAccessControlProps}[EntityPermAccessControlProps].

另外，可参考：

* xref:access-control.adoc[AccessControl]
* xref:attr-perm-access-control.adoc[AttrPermAccessControl]
* xref:specific-perm-access-control.adoc[SpecificPermAccessControl]
* link:{manual_platform}/permissions.html[Permissions in CUBA]