= Overview
:page-aliases: ROOT:index.adoc

*Jmix Frontend UI* is an alternative to the {manual_platform}/backoffice-ui[Backoffice UI]. Whereas Backoffice UI is designed primarily for internal (back-office) users, Frontend UI is targeted for external users and is more flexible in terms of layout customization. It also uses different technologies which are more familiar to frontend developers, and allows easy integration of UI libraries and components from vast JavaScript ecosystem. However, it requires better knowledge of modern frontend stack.

Frontend UI is powered by React, but you can also use a different framework (such as Angular or Vue): you can use a framework-agnostic xref:typescript-sdk:index.adoc[TypeScript SDK] for that.

We provide several tools and libraries that you can use in order to build your Frontend UI application (or *frontend client* as we call it).

== Jmix Studio

{manual_studio}[Jmix Studio] can generate a starter app and add the pieces you need such as entity browser and editor screens. Studio uses {npm_frontendGenerator}[@haulmont/jmix-front-generator] library for code generation.

== Component and Utility Libraries for React

There are two libraries for React powered frontend clients that are both used in the code generated by the Studio and can be utilized on its own. One is xref:jmix-react-core:index.adoc[Jmix React Core] which is responsible for core functionalities such as working with entities. The other is xref:jmix-react-ui:index.adoc[Jmix React UI] which contains the UI components. It uses {antDesign_base}/docs/react/introduce[Ant Design] UI kit and is used by the React client. Both libraries are available as npm packages: {npm_cubaReactCore}[@haulmont/jmix-react-core], {npm_cubaReactUi}[@haulmont/jmix-react-ui].

== Jmix REST library

{api_rest}[Jmix REST] is a library that handles the interactions with {manual_restApi}[Generic REST API]. Frontend clients use Generic REST API to communicate with the backend. However, you don't have to manually send the requests from your code. If your frontend client is based on React then xref:jmix-react-core:index.adoc[Jmix React Core] components will often handle this communication for you utilizing Jmix REST under the hood. If you are using a different framework or need more flexibility, you can use Jmix REST directly. Jmix REST is available as an npm package {npm_cubaRestJs}[@haulmont/jmix-rest].

== TypeScript SDK

xref:typescript-sdk:index.adoc[TypeScript SDK] is generated by the Studio as part of the starter application and is a TypeScript representation of project's entities, fetch plans and facades to access REST services. The SDK can be used to develop a frontend client using your favorite framework as well as for Node.js-based BFF (Backend for Frontend) development.
