= Customizing Theme

Ant Design provides a possibility to {antDesign_base}/docs/react/customize-theme[customize theme] using `less` and overriding built-in variables. You can also use these variables in your own code.

In order to do so, you will need to make some modifications to the generated app.

CAUTION: You will have to enable deprecated inline Javascript in `less` as Ant Design makes heavy use of it. link:http://lesscss.org/usage/#less-options-strict-units[Reasons for deprecation.]

- Install the required dependencies. Note that we are using https://github.com/timarney/react-app-rewired[react-app-rewired] to modify the webpack config without having to link:https://create-react-app.dev/docs/available-scripts#npm-run-eject[eject].
+
[source,bash]
----
npm i react-app-rewired less less-loader customize-cra babel-plugin-import --save-dev
----

- Create `config-overrides.js` file in the app root. The file shall look like this.
+
[source,typescript]
----
const {addLessLoader, override, fixBabelImports} = require("customize-cra");
const path = require('path');
module.exports = override(
  fixBabelImports('import', {
      libraryName: 'antd',
      libraryDirectory: 'es',
      style: true,
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: {
      'overrideTheme': `true; @import "${path.resolve(__dirname, './src/theme.less')}";`,
    },
  }),
);
----

Now you can place your overrides in `src/theme.less`:

[source,less]
----
@primary-color: #1DA57A;
----

You can use Ant Design variables in your code like this:

[source,less]
----
@import "~antd/es/style/themes/default";
body {
  background: @list-header-background;
}
----

References:

- detailed {antDesign_base}/docs/react/use-with-create-react-app#Customize-Theme[documentation] on Ant Design website

== CSS Methodology

Both the generated client and xref:cuba-react-ui:index.adoc[CUBA React UI] follow http://rscss.io[RSCSS methodology]. Additionally, we adopt Base Rules from http://smacss.com/book/type-base[SMACSS methodology].
