= Frontend Generator Reference

include::overview:partial$getting-started-note.adoc[]

NOTE: This section describes how to use the generator from CLI. You can also use many of the described features from Jmix Studio UI. The xref:commands-reference.adoc[commands description] contains information on which features are available in Studio. See {manual_studio}[Studio manual] for more details on using the generator from Studio.

Run `gen-jmix-front` (or `npx @haulmont/jmix-front-generator`) without arguments to see usage info.

....
Usage: gen-jmix-front [command] [options]

  Options:

    -v, --version  output the version number
    -h, --help     output usage information

  Commands:

    list [options]                                   List all available clients and their clients
    react-typescript:app [options]                   Generates react-typescript app
    react-typescript:blank-component [options]       Generates react-typescript blank-component
    react-typescript:entity-cards [options]          Generates react-typescript entity-cards
    react-typescript:entity-management [options]     Generates react-typescript entity-management
    sdk:all [options]                                Generates sdk all
    sdk:model [options]                              Generates sdk model
....

Run `gen-jmix-front <command> --help` to see the list of available options.

Most commands use interactive prompts to capture necessary inputs such as which entity you want to use, which {manual_platform}/data-access[fetch plan], etc. Alternatively, `answers` command line parameter can be used to provide these inputs. You may want to use it if you want to automate the generation. `answers` is a base64-encoded JSON string. See xref:commands-reference.adoc[descriptions of individual commands] for details on what shall be put inside this JSON.

Example of using `answers`:

....
gen-jmix-front react-typescript:entity-management \
  --dest ../model-playground/modules/front/src/app/car \
  --model /home/myusername/model-playground/projectModel.json \
  --dirShift ../../ \
  --answers eyJlZGl0VmlldyI6eyJuYW1lIjoiY2FyLXZpZXciLCJlbnRpdHlOYW1lIjoibXBnJENhciJ9LCJlZGl0Q29tcG9uZW50TmFtZSI6Im1wZy1jYXItZWRpdCIsImxpc3RWaWV3Ijp7Im5hbWUiOiJjYXItdmlldyIsImVudGl0eU5hbWUiOiJtcGckQ2FyIn0sImxpc3RDb21wb25lbnROYW1lIjoibXBnLWNhci1saXN0IiwibGlzdFR5cGUiOiJsaXN0IiwiZW50aXR5Ijp7Im5hbWUiOiJtcGckQ2FyIn0sIm1hbmFnZW1lbnRDb21wb25lbnROYW1lIjoibXBnLWNhci1tYW5hZ2VtZW50In0=
....
